!zone clock
; ---------------------------------------------------------------
; clock.asm — the master tick clock. tick = 1/8 beat.
; An 8.8 fixed-point "frames per tick" period is counted down every
; frame (bottom IRQ); on borrow the period is added back and one
; tick fires. Music, puppet, counts and the voice all read zp_tick.
;
; Period table (per song, generated by tools/songconv.py):
;   20 words, index = segment*10 + ntsc*5 + tempo_level
;   segment 0 = base tempo, 1 = slow deep-breathing tempo (tick 2816)
;   tempo_level 0..4 = 80 / 90 / 100 / 110 / 120 %
; ---------------------------------------------------------------

TEMPO_EVENT_TICK = 2816         ; beat 352

; A/X = period table pointer (lo/hi). Resets tick to -1 so tick 0
; fires on the next frame.
clock_start:
        sta zp_clock_tbl
        stx zp_clock_tbl+1
        lda #0
        sta clock_seg
        sta clock_acc
        sta clock_acc+1
        sta zp_tick_hold
        sta zp_tick_flag
        sta zp_tick_music
        sta zp_beat_flag
        lda #$ff
        sta zp_tick
        sta zp_tick+1
        sta zp_beat
        lda #8
        sta zp_count8
        ; fall through
clock_reload:                   ; period = tbl[seg*10 + ntsc*5 + tempo]
        lda clock_seg
        asl
        asl
        asl
        adc clock_seg
        adc clock_seg           ; seg*10
        ldx zp_ntsc
        beq +
        adc #5
+       adc clock_tempo
        asl                     ; word index
        tay
        lda (zp_clock_tbl),y
        sta clock_period
        iny
        lda (zp_clock_tbl),y
        sta clock_period+1
        rts

; TEST builds: jump the clock so that the next tick is TEST_TICK
!ifdef TEST_TICK {
clock_test_jump:
        lda #<(TEST_TICK-1)
        sta zp_tick
        lda #>(TEST_TICK-1)
        sta zp_tick+1
        lda #<((TEST_TICK-1)>>3)
        sta zp_beat             ; low byte of the beat counter
        lda #<((TEST_TICK-1)>>3)
        and #7
        clc
        adc #1
        sta zp_count8
        ; already past the tempo event?
        lda #>(TEST_TICK-1)
        cmp #>TEMPO_EVENT_TICK
        bcc +
        bne .slow
        lda #<(TEST_TICK-1)
        cmp #<TEMPO_EVENT_TICK
        bcc +
.slow:  lda #1
        sta clock_seg
        jsr clock_reload
+       rts
}

; A = tempo level 0..4
clock_set_tempo:
        cmp #5
        bcs +
        sta clock_tempo
        jsr clock_reload
+       rts

; called every frame from the bottom IRQ, before music_frame
clock_frame:
        lda zp_tick_hold
        bne .out
        dec clock_acc+1
        bpl .out                ; no tick this frame
        clc
        lda clock_acc
        adc clock_period
        sta clock_acc
        lda clock_acc+1
        adc clock_period+1
        sta clock_acc+1
        inc zp_tick
        bne +
        inc zp_tick+1
+       lda #1
        sta zp_tick_flag
        sta zp_tick_music
        lda zp_tick
        and #7
        bne .tick_only
        ; new beat
        lda zp_tick+1
        asl
        asl
        asl
        asl
        asl                     ; hi<<5
        sta zp_tmp
        lda zp_tick
        lsr
        lsr
        lsr
        ora zp_tmp
        sta zp_beat
        and #7
        clc
        adc #1
        sta zp_count8
        lda #1
        sta zp_beat_flag
.tick_only:
        ; tempo event: switch to segment 1 at the slow section
        lda zp_tick+1
        cmp #>TEMPO_EVENT_TICK
        bne .out
        lda zp_tick
        cmp #<TEMPO_EVENT_TICK
        bne .out
        lda #1
        sta clock_seg
        jsr clock_reload
.out:   rts

clock_period: !word $0300
clock_acc:    !word 0
clock_seg:    !byte 0
clock_tempo:  !byte 2           ; 100 %
