!zone music
; ---------------------------------------------------------------
; music.asm — 3-voice SID sequencer driven by the tick clock
; (clock.asm: tick = 1/8 beat, zp_tick_music is set on every tick
; and consumed here). Song data: src/gen_song1.asm / gen_song2.asm
; (generated by tools/songconv.py), instruments: src/instruments.asm.
;
; Song data format (see tools/songconv.py for the converter side)
;   header (16 bytes):  +0 three words: order lists of voices 1..3
;                       +6 word: pattern address table, low bytes
;                       +8 word: high bytes    +10 word: chord table
;                       +12 word: clock period table (20 words)
;                       +14 word: end tick (3072)
;   order list: 24 pattern indices (one per 128-tick block) + $ff
;   chord table: 3 ascending note indices per entry
;   pattern bytes (every pattern starts with INSTRUMENT, 128 ticks):
;     $00-$3f  NOTE  n, len   n = MIDI-43 (G2..F#6), gated len ticks
;     $40-$7f  CHORD c, len   c = chord index, 3-tone arpeggio (voice 3)
;     $80-$bf  REST           gate off for (low 6 bits)+1 ticks
;     $c0-$cf  INSTRUMENT k   k = index into inst_tab (instruments.asm)
;     $d0      LEGATO         next NOTE/CHORD: frequency only, no retrigger
;     $fe      end of pattern -> next order entry ($ff parks the voice)
;
; Player (music_frame, every frame from the bottom IRQ after
; clock_frame): on a tick every voice counts down v_left; at zero it
; fetches events until a NOTE/CHORD/REST is consumed. Per frame:
;   hard restart  3 frames (2 at short tick periods) before a NOTE/
;                 CHORD, once per event: AD = SR = 0, gate off. The
;                 envelope's rate-counter wrap (ADSR delay, <= 33 ms) plus
;                 the rate-0 release leave the voice silent about one
;                 frame before the note: a clean instant attack and the
;                 score's 0.92 articulation gap
;   voice 1       pulse-width ping-pong $0300..$0800 (PW_STEP/frame),
;                 vibrato after VIB_DELAY frames (12-frame triangle,
;                 step = freq>>10 -> about +-5 cents)
;   voice 2       "hammer": saw attack, triangle from the 3rd frame
;   voice 3       chord arpeggio (1 frame/tone stabs = 16.7 Hz shimmer,
;                 4 frames/tone calm harp), cutoff sweep $50..$c0
; Note-on register order: freq, PW, AD, control, SR (see sid_note: SR
; before the gate would stall the attack by 33 ms). SID writes happen
; only from music_frame (IRQ) and from the API while music_frame is
; disabled (mus_active = 0), so they never interleave. $d418 is
; written only by init/play/stop/pause/resume/seek (mus_d418 holds the
; wanted value).
;
; API (all preserve nothing; called from the main thread):
;   music_init         boot: PAL/NTSC note table -> RAM, SID globals
;   music_play         X = song 0/1: block 0, then clock_start(periods)
;   music_loop_title   X = song: loop block 0 quietly (title screen);
;                      restarts the clock at every wrap (voice_fetch_end)
;   music_seek         A = block 0..23: voices at the block start, then
;                      fast-forwarded silently to the clock's next tick
;                      (zp_tick+1), so TEST_TICK builds stay tick-exact
;   music_stop / music_pause (gates off, position kept) / music_resume
;   music_frame        IRQ, every frame
; Zero page: $30-$3f (zp_mus). Cost (cycle-exact 6502 simulation of
; both songs, PAL and NTSC): plain frame ~255 avg / 467 max, tick frame
; ~395 avg, worst case 1224 (block boundary + hard restart).
; ---------------------------------------------------------------

; --- zero page ($30-$3f) ---
zp_vptr   = zp_mus              ; 3 words: pattern pointer per voice (X = voice*2)
zp_chord  = zp_mus+6            ; word: chord table of the current song
zp_patlo  = zp_mus+8            ; word: pattern address table, low bytes
zp_pathi  = zp_mus+10           ; word: pattern address table, high bytes
zp_mtmp   = zp_mus+12           ; word: scratch pointer
zp_mt1    = zp_mus+14           ; scratch
zp_mt2    = zp_mus+15           ; scratch

; --- tunables ---
MUS_BLOCKS  = 24
PLAY_D418   = $1f               ; low-pass filter mode | volume 15
TITLE_D418  = $1a               ; title loop: volume 10
FILT_RES    = $84               ; resonance 8, filter routes voice 3 only
PW_MIN_HI   = $03               ; melody pulse-width sweep $0300..$0800
PW_MAX_HI   = $08
PW_STEP     = $28               ; per frame
VIB_DELAY   = 14                ; frames before the melody vibrato starts
FLT_MAX     = $c0               ; calm-arp cutoff sweep end

; note-on: a voice's SID registers from the descriptor (Y = inst*8).
; Order: frequency, pulse width, AD, control (gate on), SR. The SR
; register is written AFTER the gate on purpose: written before it,
; while the voice is still in its release state, it would load the
; new release period into the envelope's rate counter comparison, and
; the gate that follows a few cycles later would find the counter
; already past the attack period (9 cycles for attack 0) — the ADSR
; delay bug, a ~33 ms stall before the attack (measured in VICE).
; AD goes before the gate so the attack rate is right from cycle 0.
!macro sid_note .base, .v {
        lda v_freq_lo+.v
        sta .base+0
        lda v_freq_hi+.v
        sta .base+1
        lda inst_tab+3,y
        sta .base+2
        lda inst_tab+4,y
        sta .base+3
        lda inst_tab+1,y
        sta .base+5             ; AD
        lda inst_tab+0,y
        sta .base+4             ; control: gate on
        lda inst_tab+2,y
        sta .base+6             ; SR (see above)
}

; ---------------------------------------------------------------
; API
; ---------------------------------------------------------------

; boot (after detect_pal): note table -> RAM, SID globals, silence
!zone m_music_init
music_init:
        ldx #95                 ; 48 lo + 48 hi bytes, contiguous
        lda zp_ntsc
        bne .ntsc
-       lda note_pal_lo,x
        sta note_lo,x
        dex
        bpl -
        bmi .sid
.ntsc:  lda note_ntsc_lo,x
        sta note_lo,x
        dex
        bpl .ntsc
.sid:   lda #0
        sta mus_active
        sta mus_loop
        sta mus_silent
        sta mus_wrap
        sta arp_speed
        ldx #5
-       sta v_ctrl,x
        sta v_left,x
        sta v_gate,x
        dex
        bpl -
        jsr music_silence
        lda #FILT_RES
        sta SID_FILT_RES
        lda #0
        sta SID_FILT_LO
        lda #PLAY_D418
        sta mus_d418
        sta SID_VOL
        rts

; X = song 0/1: sequencer at block 0, clock started on the song's table
music_play:
        lda #PLAY_D418
        ldy #0                  ; no loop
        beq music_start         ; (always)
; X = song: loop block 0 (the intro phrase) quietly for the title
music_loop_title:
        lda #TITLE_D418
        ldy #1
; A = $d418 value, Y = loop flag, X = song
music_start:
        stx mus_song
        sty mus_loop
        sta mus_d418
        lda #0
        sta mus_active          ; music_frame idle while we set up
        sta mus_wrap
        jsr music_silence
        jsr music_load_song
        lda #0
        jsr music_position      ; block 0: first fetch on tick 0
        lda mus_d418
        sta SID_VOL
        jsr clock_start_song    ; tick 0 fires on the next frame
        lda #1
        sta mus_active
        rts

clock_start_song:
        lda mus_per_lo
        ldx mus_per_hi
        jmp clock_start

music_stop:
        lda #0
        sta mus_active
        sta mus_loop
        jsr music_silence
        lda mus_d418
        sta SID_VOL
        rts

music_pause:                    ; gates off, envelopes release, position kept
        lda #0
        sta mus_active
        jmp music_gates_off

music_resume:                   ; (a tick that fired since the caller released
        jsr music_retrigger     ; zp_tick_hold is still pending and gets played)
        lda mus_d418
        sta SID_VOL
        lda #1
        sta mus_active
        rts

; A = block 0..23: every voice at that block's start, then advanced
; silently until the sequencer expects the clock's next tick (zp_tick+1).
!zone m_music_seek
music_seek:
        cmp #MUS_BLOCKS
        bcc +
        lda #MUS_BLOCKS         ; past the end: everything parks
+       pha
        lda #0
        sta mus_active
        jsr music_silence
        pla
        pha
        jsr music_position
        pla                     ; seq_next = block * 128
        lsr
        sta seq_next+1
        lda #0
        ror
        sta seq_next
        lda #1
        sta mus_silent          ; no SID writes while catching up
        jsr music_catch_up      ; the bulk, interrupts enabled
        sei
        jsr music_catch_up      ; ticks that fired meanwhile (0..1)
        lda #0
        sta zp_tick_music
        sta mus_silent
        jsr music_retrigger     ; sound the notes in progress
        lda mus_d418
        sta SID_VOL
        lda #1
        sta mus_active
        cli
        rts

; advance the sequencer while seq_next <= zp_tick (and < end of song)
!zone m_music_catch_up
music_catch_up:
.loop:  lda seq_next+1
        cmp zp_tick+1
        bcc .step
        bne .done
        lda seq_next
        cmp zp_tick
        beq .step
        bcs .done
.step:  lda seq_next+1
        cmp #>TOTAL_TICKS
        bcc +
        lda seq_next
        cmp #<TOTAL_TICKS
        bcs .done
+       jsr seq_tick
        inc seq_next
        bne .loop
        inc seq_next+1
        jmp .loop
.done:  rts

; ---------------------------------------------------------------
; per frame (bottom IRQ, after clock_frame)
; ---------------------------------------------------------------
!zone m_music_frame
music_frame:
        lda mus_active
        bne +
        rts
+       lda zp_tick_music
        beq .fx
        lda #0
        sta zp_tick_music
        ldx #4                  ; = seq_tick, inlined
.loop:  dec v_left,x
        bne .next
        jsr voice_fetch
.next:  dex
        dex
        bpl .loop
        lda mus_wrap            ; title loop wrapped: restart the clock so
        beq .fx                 ; tick 0 fires again next frame (no tempo
        lda #0                  ; event, no drift; zp_tick restarts at 0)
        sta mus_wrap
        jsr clock_start_song
.fx:
!ifdef TEST_ENV3 {              ; test builds: voice 3's envelope (ENV3) once per
        lda SID_BASE+$1c        ; frame into a write of the same read-only register,
        sta SID_BASE+$1c        ; which VICE's "-sounddev dump" logs (the SID ignores it)
}
        ; fall through: fx_hard_restart -> fx_melody -> fx_bass -> fx_arp -> rts

; ---------------------------------------------------------------
; per-frame effects, chained: each one falls through to the next
; ---------------------------------------------------------------

; Hard restart, once per event, 3 frames before a NOTE/CHORD (2 when
; the tick period is shorter): AD = SR = 0, gate off. Switching the
; envelope from a slow decay/sustain rate to rate 0 makes its rate
; counter wrap first (the ADSR delay, up to 33 ms) and only then
; release to zero in ~6 ms, so the voice is silent about one frame
; before the next note and starts it with a clean, instant attack.
!zone m_fx_hard_restart
fx_hard_restart:
        lda clock_acc+1
        cmp #3
        bcs .out                ; more than 3 frames to the tick
        ldx #4
.loop:  lda v_left,x
        cmp #1
        bne .next
        lda v_hr,x
        bne .next               ; done for this event
        lda (zp_vptr,x)         ; peek at the next event byte
        cmp #$80
        bcc .do                 ; NOTE / CHORD
        cmp #$c0
        bcc .next               ; REST: let the release run
        cmp #$d0
        beq .next               ; LEGATO: no retrigger
.do:    inc v_hr,x
        ldy sid_off,x
        lda #0
        sta SID_BASE+5,y
        sta SID_BASE+6,y
        lda v_ctrl,x
        and #$fe
        sta SID_BASE+4,y
.next:  dex
        dex
        bpl .loop
.out:   ; fall through

; voice 1: pulse-width ping-pong, vibrato after VIB_DELAY frames
!zone m_fx_melody
fx_melody:
        lda v_age+0
        beq .fresh              ; note-on frame: the trigger set PW and freq
        cmp #$ff
        beq +
        inc v_age+0
+       lda v_gate+0
        beq .skip
        lda v_flags+0
        and #FLAG_MELODY
        bne .go
.skip:  jmp fx_bass
.fresh: inc v_age+0
        jmp fx_bass
.go:    lda pw_dir
        bne .down
        clc
        lda pw_lo
        adc #PW_STEP
        sta pw_lo
        lda pw_hi
        adc #0
        sta pw_hi
        cmp #PW_MAX_HI
        bcc .pw
        lda #1
        sta pw_dir
        bne .pw
.down:  sec
        lda pw_lo
        sbc #PW_STEP
        sta pw_lo
        lda pw_hi
        sbc #0
        sta pw_hi
        cmp #PW_MIN_HI
        bcs .pw
        lda #0
        sta pw_dir
.pw:    lda pw_lo
        sta SID_BASE+2
        lda pw_hi
        sta SID_BASE+3
        lda v_age+0
        cmp #VIB_DELAY
        bcc .out
        ldx vib_phase           ; 12-frame triangle: +3 steps, -6, +3
        inx
        cpx #12
        bne +
        ldx #0
+       stx vib_phase
        lda vib_dir_tab,x
        bne .sub
        clc
        lda vib_off_lo
        adc vib_step
        sta vib_off_lo
        bcc .write
        inc vib_off_hi
        jmp .write
.sub:   sec
        lda vib_off_lo
        sbc vib_step
        sta vib_off_lo
        bcs .write
        dec vib_off_hi
.write: clc
        lda v_freq_lo+0
        adc vib_off_lo
        sta SID_BASE+0
        lda v_freq_hi+0
        adc vib_off_hi
        sta SID_BASE+1
.out:   ; fall through

; voice 2: hammer — saw for two frames, then the triangle body
!zone m_fx_bass
fx_bass:
        lda v_age+2
        cmp #$ff
        beq +
        inc v_age+2
+       lda v_flags+2
        and #FLAG_HAMMER
        beq .out
        lda v_age+2
        cmp #3                  ; saw on the note-on frame and the next one
        bne .out
        lda v_ctrl+2
        and #$0f
        ora #$10
        sta v_ctrl+2
        sta SID_BASE+7+4
.out:   ; fall through

; voice 3: chord arpeggio runner, calm-section cutoff sweep
!zone m_fx_arp
fx_arp:
        lda v_gate+4
        beq .flt
        lda arp_speed
        beq .flt
        dec arp_cnt
        bne .flt
        sta arp_cnt             ; A = arp_speed
        ldx arp_idx
        inx
        cpx #3
        bne +
        ldx #0
+       stx arp_idx
        ldy arp_tones,x
        lda note_lo,y
        sta SID_BASE+14
        lda note_hi,y
        sta SID_BASE+14+1
.flt:   lda v_flags+4
        and #FLAG_SWEEP
        beq .out
        lda flt_cut
        cmp #FLT_MAX
        bcs .out
        inc flt_cut
        lda flt_cut
        sta SID_FILT_HI
.out:   rts

; ---------------------------------------------------------------
; sequencer
; ---------------------------------------------------------------

; one tick for every voice (X = voice*2 throughout the sequencer).
; A parked voice keeps counting; its pointer rests on park_byte ($ff)
; so the fetch it eventually makes just parks it again.
!zone m_seq_tick
seq_tick:
        ldx #4
.loop:  dec v_left,x
        bne .next
        jsr voice_fetch
.next:  dex
        dex
        bpl .loop
        rts

; X = voice*2: read events until a NOTE/CHORD/REST is consumed
!zone m_voice_fetch
voice_fetch_end:                ; $fe: next order entry
        inc v_order,x
        lda mus_loop
        beq +
        lda #0                  ; title loop: back to block 0; the refetch
        sta v_order,x           ; happens on the restarted clock's tick 0
        jsr voice_load_pattern
        lda #1
        sta v_left,x
        sta mus_wrap
        rts
+       jsr voice_load_pattern
        bcs .parked
        ; fall through: first event of the new pattern
voice_fetch:
.again: lda (zp_vptr,x)
        inc zp_vptr,x
        bne +
        inc zp_vptr+1,x
+       cmp #$80
        bcc .event              ; NOTE / CHORD
        cmp #$c0
        bcc .rest
        cmp #$d0
        bcc .instr
        beq .legato
        cmp #$fe
        beq voice_fetch_end
        jmp voice_park          ; $ff: end of song
.parked:
        rts
.rest:  and #$3f
        clc
        adc #1
        sta v_left,x
        lda #0
        sta v_gate,x
        sta v_hr,x
        jmp voice_gate_off
.instr: and #$0f
        asl
        asl
        asl
        sta v_inst,x            ; kept as descriptor offset (k*8)
        jmp .again
.legato:
        lda #1
        sta v_legato,x
        jmp .again
.legato_ev:                     ; legato NOTE/CHORD: frequency only
        lda #0
        sta v_legato,x
        jmp voice_setfreq
.event: sta v_note,x
        lda (zp_vptr,x)         ; length
        sta v_left,x
        inc zp_vptr,x
        bne +
        inc zp_vptr+1,x
+       lda #0
        sta v_hr,x
        lda v_legato,x
        bne .legato_ev
        lda #1
        sta v_gate,x
        ; fall through into voice_trigger

; X = voice*2: full note-on of v_note with instrument v_inst
; (also used to re-trigger after pause / seek). Preserves X.
!zone m_voice_trigger
voice_trigger:
        lda v_inst,x            ; descriptor offset (k*8)
        sta zp_mt1
        tay
        lda inst_tab+0,y
        sta v_ctrl,x
        lda inst_tab+5,y
        sta v_flags,x
        lda #0
        sta v_age,x
        lda v_note,x            ; base frequency (= voice_calc_freq, inlined)
        cmp #$40
        bcc .single
        and #$3f
        sta zp_mt2
        asl                     ; carry clear (value < $40)
        adc zp_mt2              ; chord index * 3
        tay
        lda (zp_chord),y
        sta arp_tones
        iny
        lda (zp_chord),y
        sta arp_tones+1
        iny
        lda (zp_chord),y
        sta arp_tones+2
        lda arp_tones
.single:
        tay
        lda note_lo,y
        sta v_freq_lo,x
        lda note_hi,y
        sta v_freq_hi,x
        lda mus_silent
        beq +
        rts
+       ldy zp_mt1
        cpx #2
        beq .v2
        bcs .v3
        ; --- voice 1: melody effects restart ---
        +sid_note SID_BASE, 0
        lda inst_tab+3,y
        sta pw_lo
        lda inst_tab+4,y
        sta pw_hi
        lda #0
        sta pw_dir
        sta vib_off_lo
        sta vib_off_hi
        lda #11                 ; first vibrato step is phase 0 (+)
        sta vib_phase
        lda v_freq_hi+0         ; vibrato step = freq >> 10
        lsr
        lsr
        sta vib_step
        rts
.v2:    +sid_note SID_BASE+7, 2
        rts
.v3:    lda inst_tab+6,y        ; cutoff before the gate
        sta flt_cut
        sta SID_FILT_HI
        lda inst_tab+7,y
        sta arp_speed
        clc
        adc #1                  ; fx_arp runs this frame too: tone 0 first
        sta arp_cnt
        lda #0
        sta arp_idx
        +sid_note SID_BASE+14, 4
        rts

; X = voice*2: pattern of order entry v_order -> zp_vptr, its
; INSTRUMENT byte consumed. Carry set (voice parked) at the $ff end.
!zone m_voice_load_pattern
voice_load_pattern:
        lda ord_ptr,x
        sta zp_mtmp
        lda ord_ptr+1,x
        sta zp_mtmp+1
        ldy v_order,x
        lda (zp_mtmp),y
        cmp #$ff
        beq voice_park
        tay
        lda (zp_patlo),y
        sta zp_vptr,x
        lda (zp_pathi),y
        sta zp_vptr+1,x
        lda (zp_vptr,x)         ; every pattern starts with its INSTRUMENT
        and #$0f                ; byte (songconv.py --check asserts it):
        asl                     ; consume it here, off the busy block-
        asl                     ; boundary dispatch path
        asl
        sta v_inst,x
        inc zp_vptr,x
        bne +
        inc zp_vptr+1,x
+       clc
        rts
voice_park:                     ; X = voice*2: silent until repositioned
        lda #<park_byte
        sta zp_vptr,x
        lda #>park_byte
        sta zp_vptr+1,x
        lda #0
        sta v_left,x
        sta v_gate,x
        sta v_hr,x
        sec
        ; fall through
voice_gate_off:                 ; X = voice*2 (keeps carry)
        lda mus_silent
        bne +
        ldy sid_off,x
        lda v_ctrl,x
        and #$fe
        sta SID_BASE+4,y
+       rts

; X = voice*2: base frequency of v_note (a chord also loads its
; tones into the arpeggio and uses tone 0) -> v_freq_lo/hi
!zone m_voice_calc_freq
voice_calc_freq:
        lda v_note,x
        cmp #$40
        bcc .single
        and #$3f
        sta zp_mt2
        asl                     ; carry clear (value < $40)
        adc zp_mt2              ; chord index * 3
        tay
        lda (zp_chord),y
        sta arp_tones
        iny
        lda (zp_chord),y
        sta arp_tones+1
        iny
        lda (zp_chord),y
        sta arp_tones+2
        lda arp_tones
.single:
        tay
        lda note_lo,y
        sta v_freq_lo,x
        lda note_hi,y
        sta v_freq_hi,x
        rts

; X = voice*2: legato — new frequency, envelope untouched
!zone m_voice_setfreq
voice_setfreq:
        jsr voice_calc_freq
        lda mus_silent
        bne +
        ldy sid_off,x
        lda v_freq_lo,x
        sta SID_BASE+0,y
        lda v_freq_hi,x
        sta SID_BASE+1,y
+       rts

; ---------------------------------------------------------------
; helpers
; ---------------------------------------------------------------

; header pointers of song mus_song -> RAM / zero page
!zone m_music_load_song
music_load_song:
        ldx mus_song
        lda song_hdr_lo,x
        sta zp_mtmp
        lda song_hdr_hi,x
        sta zp_mtmp+1
        ldy #0
-       lda (zp_mtmp),y         ; +0..5: order lists
        sta ord_ptr,y
        iny
        cpy #6
        bne -
        lda (zp_mtmp),y         ; +6/7: pattern lo table
        sta zp_patlo
        iny
        lda (zp_mtmp),y
        sta zp_patlo+1
        iny
        lda (zp_mtmp),y         ; +8/9: pattern hi table
        sta zp_pathi
        iny
        lda (zp_mtmp),y
        sta zp_pathi+1
        iny
        lda (zp_mtmp),y         ; +10/11: chords
        sta zp_chord
        iny
        lda (zp_mtmp),y
        sta zp_chord+1
        iny
        lda (zp_mtmp),y         ; +12/13: period table
        sta mus_per_lo
        iny
        lda (zp_mtmp),y
        sta mus_per_hi
        rts

; A = block 0..24: every voice at the block start, fetch on the next tick
!zone m_music_position
music_position:
        sta zp_mt2
        ldx #4
-       lda zp_mt2
        sta v_order,x
        lda #1
        sta v_left,x
        lda #0
        sta v_gate,x
        sta v_legato,x
        sta v_age,x
        sta v_hr,x
        jsr voice_load_pattern  ; parks at the $ff terminator
        dex
        dex
        bpl -
        lda #0
        sta arp_speed
        rts

; re-trigger every voice that is inside a NOTE/CHORD
!zone m_music_retrigger
music_retrigger:
        ldx #4
-       lda v_gate,x
        beq +
        jsr voice_trigger
+       dex
        dex
        bpl -
        rts

; immediate silence: AD = SR = 0, gates off (release 0 = 6 ms)
!zone m_music_silence
music_silence:
        ldx #4
-       ldy sid_off,x
        lda #0
        sta SID_BASE+5,y
        sta SID_BASE+6,y
        lda v_ctrl,x
        and #$fe
        sta SID_BASE+4,y
        dex
        dex
        bpl -
        rts

; gates off, envelopes keep their release
!zone m_music_gates_off
music_gates_off:
        ldx #4
-       ldy sid_off,x
        lda v_ctrl,x
        and #$fe
        sta SID_BASE+4,y
        dex
        dex
        bpl -
        rts

; ---------------------------------------------------------------
; data
; ---------------------------------------------------------------
song_hdr_lo: !byte <song1, <song2
song_hdr_hi: !byte >song1, >song2
sid_off:     !byte 0, 0, 7, 0, 14, 0        ; SID register offset (X = voice*2)
park_byte:   !byte $ff                      ; a parked voice's pattern
vib_dir_tab: !byte 0,0,0, 1,1,1,1,1,1, 0,0,0

mus_d418:    !byte PLAY_D418    ; byte the music wants in $d418 (vol | filter mode)
mus_active:  !byte 0            ; 1 = music_frame runs the sequencer / effects
mus_silent:  !byte 0            ; 1 = suppress SID writes (seek fast-forward)
mus_loop:    !byte 0            ; 1 = loop block 0 (title)
mus_wrap:    !byte 0            ; set by the loop wrap, restarts the clock
mus_song:    !byte 0
mus_per_lo:  !byte 0            ; current song's period table
mus_per_hi:  !byte 0
seq_next:    !word 0            ; seek: tick the sequencer expects next
ord_ptr:     !fill 6, 0         ; order-list pointers (lo, hi per voice)

; per-voice state, index X = voice*2 (0, 2, 4)
v_left:      !fill 6, 0         ; ticks until the next fetch
v_note:      !fill 6, 0         ; current event byte (note or $40+chord)
v_inst:      !fill 6, 0         ; instrument * 8 (descriptor offset)
v_legato:    !fill 6, 0
v_gate:      !fill 6, 0         ; 1 = inside a NOTE/CHORD
v_order:     !fill 6, 0
v_ctrl:      !fill 6, 0         ; waveform | gate as last written
v_flags:     !fill 6, 0
v_age:       !fill 6, 0         ; frames since note-on (saturating)
v_hr:        !fill 6, 0         ; 1 = hard restart done for the current event
v_freq_lo:   !fill 6, 0
v_freq_hi:   !fill 6, 0

; effect state
pw_lo:       !byte 0            ; voice 1 pulse width
pw_hi:       !byte 0
pw_dir:      !byte 0
vib_phase:   !byte 0
vib_step:    !byte 0
vib_off_lo:  !byte 0
vib_off_hi:  !byte 0
arp_tones:   !byte 0, 0, 0      ; voice 3 chord
arp_idx:     !byte 0
arp_cnt:     !byte 0
arp_speed:   !byte 0
flt_cut:     !byte 0

; note table of the running system (copied by music_init), 48+48
note_lo:     !fill 48, 0
note_hi:     !fill 48, 0
